version: '2'

services:
  account_db:
    image: "mongo:3.2.20-jessie"
    env_file: .env
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"

  app:
    image: node:9.11.2-jessie
    env_file: .env
    working_dir: /home/node/app
    restart: always
    user: "node"
    depends_on:
      - account_db
    volumes:
      - ./app:/home/node/app
    entrypoint: /home/node/app/entrypoint.sh
    ports:
      - "3000:3000"
