version: '3'

services:
  db:
    image: "mongo:3.2.20-jessie"
    env_file: .env
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"

  app:
    image: node:9.11.2-jessie
    env_file: .env
    working_dir: /home/node/app
    restart: always
    user: "node"
    depends_on:
      - db
    volumes:
      - ./app:/home/node/app
    entrypoint: /home/node/app/entrypoint.sh
    ports:
      - "3000:3000"

volumes:
  dbdata: