version: '3'

services:
  db:
    image: "mongo:3.2.20-jessie"
    env_file: .env
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"

  app:
    build: ./app
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./app:/home/node/app
    ports:
      - "3000:3000"
    entrypoint:
      /home/node/app/entrypoint.sh

volumes:
  dbdata: